version: '3.9'

services:
  curd-web-go:
    container_name: curd-web-go
    build: .
    ports:
      - "8000:8080"
    environment:
      DATABASE_URL: "host=db user=postgres password=admin123 dbname=product_db sslmode=disable"
    depends_on:
      - db

  db:
    container_name: postgres-db
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: admin123
      POSTGRES_USER: postgres
      POSTGRES_DB: product_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

